application: all-about-python  # FIXME: Replace this with your application id
version: 1
runtime: python27
api_version: 1
threadsafe: false

builtins:
- remote_api: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
- name: setuptools
  version: latest


handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /_ah/dev_admin(/.*)?  # provides interactive console
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
  secure: always
- url: /favicon.ico
  static_files: assets/img/favicon.ico
  upload: assets/img/favicon.ico
- url: /.*
  script: main.app

# The skip_files element specifies which files in the application directory 
# are not to be uploaded to App Engine. The value is either a regular 
# expression, or a list of regular expressions. Any filename that matches 
# any of the regular expression is omitted from the list of files to upload 
# when the application is uploaded.
# do not upload file like .py,.csv, or name contain string tmp
skip_files:
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.csv
- tmp
- tests
- .*?~$